Fix error with zombies turning and increase their turn sensitivity
Error: angles only stay within 0-360, so if their current angle is 10,
and their next angle is 350, they will go from 10 -> 350, instead of
going from 10->0, and then 360->350. Fix this